app = "jkmp-backend-matchmaking"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 16000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 2048
    soft_limit = 1024

  [[services.ports]]
    port = "10069"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
