[package]
name = "jkmp"
version = "0.1.0"
authors = ["Skipcast", "amPerl"]
edition = "2021"

[dependencies]
tokio-util = { version = "0.6", features = ["time", "codec"] }
anyhow = "1.0"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
bytes = "1.1"